"""Adapter for scalar codebooks generated by upstream quantization projects."""

from __future__ import annotations

from dataclasses import dataclass

import torch

from .base_quantizer import BaseQuantizer, QuantResult


@dataclass
class CodebookContext:
    """Upstream codebook centers for the current layer."""

    precomputed_centers: torch.Tensor | None = None


class BaseCodebook(BaseQuantizer):
    """Consume upstream per-row codebooks and expose RBVT's QuantResult format."""

    def __init__(
        self,
        name: str,
        bits: int,
        group_size: int = -1,
        eps: float = 1e-12,
        **upstream_options,
    ):
        if bits not in (3, 4):
            raise ValueError(f"Codebook bits must be 3 or 4, got {bits}")
        if group_size == 0 or group_size < -1:
            raise ValueError(f"group_size must be -1 or positive, got {group_size}")

        super().__init__(bits=bits, block_size=group_size)
        self.name = name
        self.group_size = group_size
        self.num_levels = 2**bits
        self.eps = eps
        self.upstream_options = dict(upstream_options)
        for key, value in upstream_options.items():
            setattr(self, key, value)
        self.context = CodebookContext()
        self._q_levels = torch.linspace(-1.0, 1.0, self.num_levels)

    @property
    def q_levels(self) -> torch.Tensor:
        return self._q_levels

    def set_context(self, context: CodebookContext | None) -> "BaseCodebook":
        self.context = context or CodebookContext()
        return self

    @torch.no_grad()
    def quantize(self, W: torch.Tensor, row_chunk: int = 1024) -> QuantResult:
        if W.ndim != 2:
            raise ValueError(f"Codebook quantization expects a matrix, got {tuple(W.shape)}")

        device = W.device
        out_features, in_features = W.shape
        block_size = in_features if self.group_size == -1 else self.group_size
        n_blocks = (in_features + block_size - 1) // block_size
        precomputed = self.context.precomputed_centers
        if precomputed is None:
            raise RuntimeError(
                f"{self.name} codebooks must be generated by the upstream repository "
                "before quantization"
            )
        expected = (out_features, n_blocks, self.num_levels)
        if tuple(precomputed.shape) != expected:
            raise ValueError(
                f"Precomputed centers have shape {tuple(precomputed.shape)}, "
                f"expected {expected}"
            )
        precomputed = torch.sort(
            precomputed.to(device=device, dtype=torch.float32),
            dim=-1,
        ).values

        W_dequant = torch.empty_like(W)
        indices = torch.empty(
            out_features,
            in_features,
            dtype=torch.long,
            device=device,
        )
        block_codebooks = torch.empty(
            out_features,
            n_blocks,
            self.num_levels,
            dtype=torch.float32,
            device=device,
        )
        block_scales = torch.empty(
            out_features,
            n_blocks,
            dtype=torch.float32,
            device=device,
        )

        for row_start in range(0, out_features, row_chunk):
            row_end = min(row_start + row_chunk, out_features)
            rows = W[row_start:row_end].float()

            for block_index in range(n_blocks):
                column_start = block_index * block_size
                column_end = min(column_start + block_size, in_features)
                values = rows[:, column_start:column_end]
                centers = precomputed[row_start:row_end, block_index]

                distances = (values.unsqueeze(-1) - centers.unsqueeze(1)).abs()
                block_indices = distances.argmin(dim=-1)
                dequantized = torch.gather(centers, 1, block_indices)

                W_dequant[row_start:row_end, column_start:column_end] = dequantized.to(W.dtype)
                indices[row_start:row_end, column_start:column_end] = block_indices
                block_codebooks[row_start:row_end, block_index] = centers
                block_scales[row_start:row_end, block_index] = (
                    centers.abs().amax(dim=1).clamp_min(self.eps)
                )

        return QuantResult(
            W_dequant=W_dequant,
            indices=indices,
            q_levels=self.q_levels.to(device),
            block_scales=block_scales,
            block_size=block_size,
            block_codebooks=block_codebooks,
            block_zeros=None,
        )

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}(name={self.name!r}, bits={self.bits}, "
            f"group_size={self.group_size}, upstream_options={self.upstream_options})"
        )
